_categories = {'Computer Crime News Updates': {'description': '<a href="http://hermes.circ.gwu.edu/archives/cybercrime.html">Computer Crime News Updates</a> by <a href="mailto:okerr@LAW.GWU.EDU">Orin S. Kerr</a>,  Associate Professor George Washington University Law School\n\n<b>This is an internal Experiment - stay away</b>',
                                              'displayName': 'Computer Crime News Updates',
                                              'fileName': 'computerCrimeNewsUpdates',
                                              'htmlUrl': 'http://md.hudora.de/blog/categories/computerCrimeNewsUpdates/',
                                              'language': 'none',
                                              'rssUrl': 'http://md.hudora.de/blog/categories/computerCrimeNewsUpdates/rss.xml'},
              'DoS': {'description': '',
                      'displayName': 'DoS',
                      'fileName': 'dos',
                      'htmlUrl': 'http://md.hudora.de/blog/categories/dos/',
                      'language': 'none',
                      'rssUrl': 'http://md.hudora.de/blog/categories/dos/rss.xml'},
              'EULAs': {'description': '',
                        'displayName': 'EULAs',
                        'fileName': 'eulas',
                        'htmlUrl': 'http://md.hudora.de/blog/categories/eulas/',
                        'language': 'none',
                        'rssUrl': 'http://md.hudora.de/blog/categories/eulas/rss.xml'},
              'FUD': {'description': 'fear, unceartenty, doubt: statistics about computer crime, talk about cyberterror et. al.',
                      'displayName': 'FUD',
                      'fileName': 'fud',
                      'htmlUrl': 'http://md.hudora.de/blog/categories/fud/',
                      'language': 'none',
                      'rssUrl': 'http://md.hudora.de/blog/categories/fud/rss.xml'},
              'Radio Nights': {'description': '"Wenn die Nacht am tiefsten ist, ist der Tag am n&auml;chsten". Weblogsoftware and me.',
                               'displayName': 'Radio Nights',
                               'fileName': 'radioNights',
                               'htmlUrl': 'http://md.hudora.de/blog/categories/radioNights/',
                               'language': 'none',
                               'rssUrl': 'http://md.hudora.de/blog/categories/radioNights/rss.xml'},
              'books': {'description': 'books about computer crime and the like',
                        'displayName': 'books',
                        'fileName': 'books',
                        'htmlUrl': 'http://md.hudora.de/blog/categories/books/',
                        'language': 'none',
                        'rssUrl': 'http://md.hudora.de/blog/categories/books/rss.xml'},
              'computerforensics': {'description': 'Investigations about Cybercrime',
                                    'displayName': 'computerforensics',
                                    'fileName': 'computerforensics',
                                    'htmlUrl': 'http://md.hudora.de/blog/categories/computerforensics/',
                                    'language': 'none',
                                    'rssUrl': 'http://md.hudora.de/blog/categories/computerforensics/rss.xml'},
              'crackdown': {'description': 'police, survilance and prosecution of computercrime',
                            'displayName': 'crackdown',
                            'fileName': 'crackdown',
                            'htmlUrl': 'http://md.hudora.de/blog/categories/crackdown/',
                            'language': 'none',
                            'rssUrl': 'http://md.hudora.de/blog/categories/crackdown/rss.xml'},
              'crime prevention': {'description': '',
                                   'displayName': 'crime prevention',
                                   'fileName': 'crimePrevention',
                                   'htmlUrl': 'http://md.hudora.de/blog/categories/crimePrevention/',
                                   'language': 'none',
                                   'rssUrl': 'http://md.hudora.de/blog/categories/crimePrevention/rss.xml'},
              'cybercriminals': {'description': 'Researchers, Hackers, Crackers, Criminals - Who are they and why do they do what they do?',
                                 'displayName': 'cybercriminals',
                                 'fileName': 'cybercriminals',
                                 'htmlUrl': 'http://md.hudora.de/blog/categories/cybercriminals/',
                                 'language': 'none',
                                 'rssUrl': 'http://md.hudora.de/blog/categories/cybercriminals/rss.xml'},
              'cyberwar': {'description': '',
                           'displayName': 'cyberwar',
                           'fileName': 'cyberwar',
                           'htmlUrl': 'http://md.hudora.de/blog/categories/cyberwar/',
                           'language': 'en',
                           'rssUrl': 'http://md.hudora.de/blog/categories/cyberwar/rss.xml'},
              'cyberweapons': {'description': '',
                               'displayName': 'cyberweapons',
                               'fileName': 'cyberweapons',
                               'htmlUrl': 'http://md.hudora.de/blog/categories/cyberweapons/',
                               'language': 'none',
                               'rssUrl': 'http://md.hudora.de/blog/categories/cyberweapons/rss.xml'},
 'defacements': {'description': '',
                 'displayName': 'defacements',
                 'fileName': 'defacements',
                 'htmlUrl': 'http://md.hudora.de/blog/categories/defacements/',
                 'language': 'none',
                 'rssUrl': 'http://md.hudora.de/blog/categories/defacements/rss.xml'},
              'deutsch': {'description': 'german language stuff: Computerkriminalitaet',
             'displayName': 'deutsch',
                          'fileName': 'deutsch',
             'htmlUrl': 'http://md.hudora.de/blog/categories/deutsch/',
                          'language': 'none',
                          'rssUrl': 'http://md.hudora.de/blog/categories/deutsch/rss.xml'},
              'discosure': {'description': '',
                            'displayName': 'discosure',
                            'fileName': 'discosure',
               'htmlUrl': 'http://md.hudora.de/blog/categories/discosure/',
                            'language': 'none',
                            'rssUrl': 'http://md.hudora.de/blog/categories/discosure/rss.xml'},
              'dumm oder faul': {'description': '',
                                 'displayName': 'dumm oder faul',
                                 'fileName': 'dummOderFaul',
                                 'htmlUrl': 'http://md.hudora.de/blog/categories/dummOderFaul/',
                                 'language': 'none',
                                 'rssUrl': 'http://md.hudora.de/blog/categories/dummOderFaul/rss.xml'},
              'espionage': {'description': '',
                            'displayName': 'espionage',
                            'fileName': 'espionage',
                            'htmlUrl': 'http://md.hudora.de/blog/categories/espionage/',
                            'language': 'none',
                            'rssUrl': 'http://md.hudora.de/blog/categories/espionage/rss.xml'},
              'events': {'description': 'computercrime related conferences etc.',
                         'displayName': 'events',
                         'fileName': 'events',
                         'htmlUrl': 'http://md.hudora.de/blog/categories/events/',
                         'language': 'none',
                         'rssUrl': 'http://md.hudora.de/blog/categories/events/rss.xml'},
              'fnord!': {'description': '',
                         'displayName': 'fnord!',
                         'fileName': 'fnord',
                         'htmlUrl': 'http://md.hudora.de/blog/categories/fnord/',
                         'language': 'none',
                         'rssUrl': 'http://md.hudora.de/blog/categories/fnord/rss.xml'},
              'hacktivism': {'description': 'political actions mediated by technology',
                             'displayName': 'hacktivism',
                             'fileName': 'hacktivism',
                             'htmlUrl': 'http://md.hudora.de/blog/categories/hacktivism/',
                             'language': 'en',
                             'rssUrl': 'http://md.hudora.de/blog/categories/hacktivism/rss.xml'},
              'hatespeech': {'description': '',
                             'displayName': 'hatespeech',
                             'fileName': 'hatespeech',
                             'htmlUrl': 'http://md.hudora.de/blog/categories/hatespeech/',
                             'language': 'none',
                             'rssUrl': 'http://md.hudora.de/blog/categories/hatespeech/rss.xml'},
              'heim und herd': {'description': 'Geschichten aus dem Leben von Neal, Nicky und Max.',
                                'displayName': 'heim und herd',
                                'fileName': 'heimUndHerd',
                                'htmlUrl': 'http://md.hudora.de/dornet/blog/',
                                'language': 'de',
                                'rssUrl': 'http://md.hudora.de/dornet/blog/rss.xml'},
              'identity theft': {'description': '',
                                 'displayName': 'identity theft',
                                 'fileName': 'identityTheft',
                                 'htmlUrl': 'http://md.hudora.de/blog/categories/identityTheft/',
                                 'language': 'none',
                                 'rssUrl': 'http://md.hudora.de/blog/categories/identityTheft/rss.xml'},
              'incidents': {'description': 'computer related incidents',
                            'displayName': 'incidents',
                            'fileName': 'incidents',
                            'htmlUrl': 'http://md.hudora.de/blog/categories/incidents/',
                            'language': 'none',
                            'rssUrl': 'http://md.hudora.de/blog/categories/incidents/rss.xml'},
              'information prohibition': {'description': 'Things you are not allowed to think or talk or read about.',
                                          'displayName': 'information prohibition',
                                          'fileName': 'informationProhibition',
                                          'htmlUrl': 'http://md.hudora.de/blog/categories/informationProhibition/',
                                          'language': 'none',
                                          'rssUrl': 'http://md.hudora.de/blog/categories/informationProhibition/rss.xml'},
              'interlectual rights': {'description': 'so called intellectual property',
                                      'displayName': 'interlectual rights',
                                      'fileName': 'interlectualRights',
                                      'htmlUrl': 'http://md.hudora.de/blog/categories/interlectualRights/',
                                      'language': 'en',
                                      'rssUrl': 'http://md.hudora.de/blog/categories/interlectualRights/rss.xml'},
              'lawmaking': {'description': 'and laws in the making',
                            'displayName': 'lawmaking',
                            'fileName': 'lawmaking',
                            'htmlUrl': 'http://md.hudora.de/blog/categories/lawmaking/',
                            'language': 'none',
                            'rssUrl': 'http://md.hudora.de/blog/categories/lawmaking/rss.xml'},
              'legalese': {'description': 'scholary writing regarding cybercrime and the like',
                           'displayName': 'legalese',
                           'fileName': 'legalese',
                           'htmlUrl': 'http://md.hudora.de/blog/categories/legalese/',
                           'language': 'none',
                           'rssUrl': 'http://md.hudora.de/blog/categories/legalese/rss.xml'},
              'liability': {'description': '',
                            'displayName': 'liability',
                            'fileName': 'liability',
                            'htmlUrl': 'http://md.hudora.de/blog/categories/liability/',
                            'language': 'none',
                            'rssUrl': 'http://md.hudora.de/blog/categories/liability/rss.xml'},
              'malware': {'description': '',
                          'displayName': 'malware',
                          'fileName': 'malware',
                          'htmlUrl': 'http://md.hudora.de/blog/categories/malware/',
                          'language': 'none',
                          'rssUrl': 'http://md.hudora.de/blog/categories/malware/rss.xml'},
              'misc': {'description': 'foo, bar and all the others',
                       'displayName': 'misc',
                       'fileName': 'misc',
                       'htmlUrl': 'http://md.hudora.de/blog/categories/misc/',
                       'language': 'none',
                       'rssUrl': 'http://md.hudora.de/blog/categories/misc/rss.xml'},
              'nifty hacks': {'description': 'tools and toys',
                              'displayName': 'nifty hacks',
                              'fileName': 'niftyHacks',
                              'htmlUrl': 'http://md.hudora.de/blog/categories/niftyHacks/',
                              'language': 'none',
                              'rssUrl': 'http://md.hudora.de/blog/categories/niftyHacks/rss.xml'},
              'organized crime': {'description': '',
                                  'displayName': 'organized crime',
                                  'fileName': 'organizedCrime',
                                  'htmlUrl': 'http://md.hudora.de/blog/categories/organizedCrime/',
                                  'language': 'none',
                                  'rssUrl': 'http://md.hudora.de/blog/categories/organizedCrime/rss.xml'},
              'original content': {'description': 'stuff written by Max Dornseif relating to Computer Crime',
                                   'displayName': 'original content',
                                   'fileName': 'originalContent',
                                   'htmlUrl': 'http://md.hudora.de/blog/categories/originalContent/',
                                   'language': 'none',
                                   'rssUrl': 'http://md.hudora.de/blog/categories/originalContent/rss.xml'},
              'our Profession': {'description': 'the legal profession',
                                 'displayName': 'our Profession',
                                 'fileName': 'ourProfession',
                                 'htmlUrl': 'http://md.hudora.de/blog/categories/ourProfession/',
                                 'language': 'none',
                                 'rssUrl': 'http://md.hudora.de/blog/categories/ourProfession/rss.xml'},
              'p0rn': {'description': '',
                       'displayName': 'p0rn',
          'fileName': 'p0rn',
                       'htmlUrl': 'http://md.hudora.de/blog/categories/p0rn/',
                       'language': 'none',
                       'rssUrl': 'http://md.hudora.de/blog/categories/p0rn/rss.xml'},
              'payment': {'description': '',
                          'displayName': 'payment',
                          'fileName': 'payment',
                          'htmlUrl': 'http://md.hudora.de/blog/categories/payment/',
                          'language': 'none',
                          'rssUrl': 'http://md.hudora.de/blog/categories/payment/rss.xml'},
              'policy': {'description': 'policymaking on cybercrime and computer security',
                         'displayName': 'policy',
                         'fileName': 'policy',
                         'htmlUrl': 'http://md.hudora.de/blog/categories/policy/',
                         'language': 'none',
                         'rssUrl': 'http://md.hudora.de/blog/categories/policy/rss.xml'},
              'politics and ethics': {'description': 'opinions about cybercrime, lawmaking and the like',
                                      'displayName': 'politics and ethics',
                                      'fileName': 'politicsAndEthics',
                                      'htmlUrl': 'http://md.hudora.de/blog/categories/politicsAndEthics/',
                                      'language': 'none',
                                      'rssUrl': 'http://md.hudora.de/blog/categories/politicsAndEthics/rss.xml'},
              'privacy': {'description': 'privacy robbery and strategies against it',
                          'displayName': 'privacy',
                          'fileName': 'privacy',
                          'htmlUrl': 'http://md.hudora.de/blog/categories/privacy/',
                          'language': 'none',
                          'rssUrl': 'http://md.hudora.de/blog/categories/privacy/rss.xml'},
              'punishment': {'description': '',
                             'displayName': 'punishment',
                             'fileName': 'punishment',
                             'htmlUrl': 'http://md.hudora.de/blog/categories/punishment/',
                             'language': 'none',
                             'rssUrl': 'http://md.hudora.de/blog/categories/punishment/rss.xml'},
              'reporting of cybercrime': {'description': '',
                                          'displayName': 'reporting of cybercrime',
                                          'fileName': 'reportingOfCybercrime',
                                          'htmlUrl': 'http://md.hudora.de/blog/categories/reportingOfCybercrime/',
                                          'language': 'none',
                                          'rssUrl': 'http://md.hudora.de/blog/categories/reportingOfCybercrime/rss.xml'},
              'risks': {'description': '',
                        'displayName': 'risks',
                        'fileName': 'risks',
                        'htmlUrl': 'http://md.hudora.de/blog/categories/risks/',
                        'language': 'none',
                        'rssUrl': 'http://md.hudora.de/blog/categories/risks/rss.xml'},
              'security': {'description': 'security whatever that means',
                           'displayName': 'security',
                           'fileName': 'security',
                           'htmlUrl': 'http://md.hudora.de/blog/categories/security/',
                           'language': 'none',
                           'rssUrl': 'http://md.hudora.de/blog/categories/security/rss.xml'},
              'snakeoil': {'description': '',
                           'displayName': 'snakeoil',
                           'fileName': 'snakeoil',
                           'htmlUrl': 'http://md.hudora.de/blog/categories/snakeoil/',
                           'language': 'none',
                           'rssUrl': 'http://md.hudora.de/blog/categories/snakeoil/rss.xml'},
              'teaching': {'description': 'teaching and learning',
                           'displayName': 'teaching',
                           'fileName': 'teaching',
                           'htmlUrl': 'http://md.hudora.de/blog/categories/teaching/',
                           'language': 'none',
                           'rssUrl': 'http://md.hudora.de/blog/categories/teaching/rss.xml'},
              'telephone': {'description': '',
                            'displayName': 'telephone',
                            'fileName': 'telephone',
                            'htmlUrl': 'http://md.hudora.de/blog/categories/telephone/',
                            'language': 'none',
                            'rssUrl': 'http://md.hudora.de/blog/categories/telephone/rss.xml'},
              'thoughtcrime': {'description': '',
                               'displayName': 'thoughtcrime',
                               'fileName': 'thoughtcrime',
                               'htmlUrl': 'http://md.hudora.de/blog/categories/thoughtcrime/',
                               'language': 'none',
                               'rssUrl': 'http://md.hudora.de/blog/categories/thoughtcrime/rss.xml'},
              'transnational': {'description': '',
                                'displayName': 'transnational',
                                'fileName': 'transnational',
                                'htmlUrl': 'http://md.hudora.de/blog/categories/transnational/',
                                'language': 'none',
                                'rssUrl': 'http://md.hudora.de/blog/categories/transnational/rss.xml'},
              'trials': {'description': 'computer crime at the courts (or at least in prosecution)',
                         'displayName': 'trials',
                         'fileName': 'trials',
                         'htmlUrl': 'http://md.hudora.de/blog/categories/trials/',
                         'language': 'none',
                         'rssUrl': 'http://md.hudora.de/blog/categories/trials/rss.xml'},
              'unwanted contact': {'description': '',
                                   'displayName': 'unwanted contact',
                                   'fileName': 'unwantedContact',
                                   'htmlUrl': 'http://md.hudora.de/blog/categories/unwantedContact/',
                                   'language': 'none',
                                   'rssUrl': 'http://md.hudora.de/blog/categories/unwantedContact/rss.xml'},
              'vandalim': {'description': '',
                           'displayName': 'vandalim',
                           'fileName': 'vandalim',
                           'htmlUrl': 'http://md.hudora.de/blog/categories/vandalim/',
                           'language': 'none',
                           'rssUrl': 'http://md.hudora.de/blog/categories/vandalim/rss.xml'},
              'white collar': {'description': 'crime and puzzlement',
                               'displayName': 'white collar',
                               'fileName': 'whiteCollar',
                               'htmlUrl': 'http://md.hudora.de/blog/categories/whiteCollar/',
                               'language': 'none',
                               'rssUrl': 'http://md.hudora.de/blog/categories/whiteCollar/rss.xml'}}

def getFilename(cat):
    return _categories[cat]['fileName']

def getDisplayname(cat):
    return _categories[cat]['displayName']
    
