#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: TvLuserland.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxWindows' modules
from wxPython.wx import *

# Window functions

ID_TEXT = 10000
ID_POSTTITLE = 10001
ID_POSTLINK = 10002
ID_POSTTEXT = 10003
ID_TEX = 10004
ID_POSTINGTEXT = 10005
ID_POSTINGGAUGE = 10006
wxID_POST = 10007

def EditPostFunc( parent, call_fit = true, set_sizer = true ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item1 = wxBoxSizer( wxHORIZONTAL )
    parent.previewsizer = item1
    
    item0.AddSizer( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 10 )

    item2 = wxFlexGridSizer( 0, 2, 0, 0 )
    item2.AddGrowableCol( 1 )
    item2.AddGrowableRow( 2 )
    
    item3 = wxStaticText( parent, ID_TEXT, "Title", wxDefaultPosition, wxDefaultSize, 0 )
    item2.AddWindow( item3, 0, wxALIGN_CENTRE|wxALL, 5 )

    item4 = wxTextCtrl( parent, ID_POSTTITLE, "", wxDefaultPosition, wxSize(300,-1), 0 )
    item2.AddWindow( item4, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item5 = wxStaticText( parent, ID_TEXT, "Link", wxDefaultPosition, wxDefaultSize, 0 )
    item2.AddWindow( item5, 0, wxALIGN_CENTRE|wxALL, 5 )

    item6 = wxTextCtrl( parent, ID_POSTLINK, "", wxDefaultPosition, wxSize(300,-1), 0 )
    item2.AddWindow( item6, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item7 = wxStaticText( parent, ID_TEXT, "Text", wxDefaultPosition, wxDefaultSize, 0 )
    item2.AddWindow( item7, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item8 = wxTextCtrl( parent, ID_POSTTEXT, "", wxDefaultPosition, wxSize(300,-1), wxTE_MULTILINE|wxTE_RICH )
    item2.AddWindow( item8, 0, wxGROW|wxALL, 5 )

    item9 = wxStaticText( parent, ID_TEX, "Categories", wxDefaultPosition, wxDefaultSize, 0 )
    item2.AddWindow( item9, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item10 = wxFlexGridSizer( 0, 4, 0, 0 )
    item10.AddGrowableCol( 0 )
    item10.AddGrowableCol( 1 )
    item10.AddGrowableCol( 2 )
    item10.AddGrowableCol( 3 )
    parent.catsizer = item10
    
    item2.AddSizer( item10, 0, wxALIGN_CENTRE|wxALL, 5 )

    item0.AddSizer( item2, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 10 )

    item11 = wxBoxSizer( wxHORIZONTAL )
    
    item12 = wxStaticText( parent, ID_POSTINGTEXT, "", wxDefaultPosition, wxDefaultSize, wxALIGN_RIGHT )
    item11.AddWindow( item12, 0, wxALIGN_CENTRE|wxALL, 5 )

    item13 = wxGauge( parent, ID_POSTINGGAUGE, 100, wxDefaultPosition, wxSize(100,-1), 0 )
    item13.Enable(false)
    item11.AddWindow( item13, 0, wxALIGN_CENTRE|wxALL, 5 )

    item11.AddSpacer( 20, 20, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item14 = wxButton( parent, wxID_CANCEL, "Cancel", wxDefaultPosition, wxDefaultSize, 0 )
    item11.AddWindow( item14, 0, wxALIGN_CENTRE|wxALL, 5 )

    item15 = wxButton( parent, wxID_POST, "Post", wxDefaultPosition, wxDefaultSize, 0 )
    item15.SetDefault()
    item11.AddWindow( item15, 0, wxALIGN_CENTRE|wxALL, 5 )

    item0.AddSizer( item11, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 10 )

    item0.AddSpacer( 10, 10, 0, wxALIGN_CENTRE|wxALL, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_SERVICETREE = 10008
ID_LINE = 10009
ID_NEWPOST = 10010
ID_REFRESH = 10011
ID_NEWSPANE = 10012

def ReadNewsFunc( parent, call_fit = true, set_sizer = true ):
    item0 = wxBoxSizer( wxHORIZONTAL )
    
    item1 = wxTreeCtrl( parent, ID_SERVICETREE, wxDefaultPosition, wxSize(120,160), wxTR_HAS_BUTTONS|wxTR_LINES_AT_ROOT|wxNO_BORDER )
    item0.AddWindow( item1, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item2 = wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(-1,20), wxLI_VERTICAL )
    item0.AddWindow( item2, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item3 = wxBoxSizer( wxVERTICAL )
    
    item4 = wxBoxSizer( wxHORIZONTAL )
    
    item5 = wxButton( parent, ID_NEWPOST, "New Post", wxDefaultPosition, wxDefaultSize, 0 )
    item4.AddWindow( item5, 0, wxALIGN_CENTRE|wxALL, 5 )

    item6 = wxButton( parent, ID_REFRESH, "Refresh", wxDefaultPosition, wxDefaultSize, 0 )
    item4.AddWindow( item6, 0, wxALIGN_CENTRE|wxALL, 5 )

    item3.AddSizer( item4, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item7 = parent.newspane
    item3.AddWindow( item7, 0, wxALIGN_CENTRE|wxALL, 5 )

    item0.AddSizer( item3, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_HTML = 10013
ID_KILL = 10014
ID_POST = 10015
ID_EDIT = 10016

def NewsItemFunc( parent, call_fit = true, set_sizer = true ):
    item0 = wxBoxSizer( wxHORIZONTAL )
    
    item1 = wxBoxSizer( wxHORIZONTAL )
    parent.itemsizer = item1
    
    item2 = parent.html
    item1.AddWindow( item2, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxLEFT|wxBOTTOM, 15 )

    item3 = wxBoxSizer( wxVERTICAL )
    
    item4 = wxButton( parent, ID_KILL, "Kill", wxDefaultPosition, wxDefaultSize, 0 )
    item3.AddWindow( item4, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item5 = wxButton( parent, ID_POST, "Post", wxDefaultPosition, wxDefaultSize, 0 )
    item3.AddWindow( item5, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item6 = wxButton( parent, ID_EDIT, "Edit", wxDefaultPosition, wxDefaultSize, 0 )
    item3.AddWindow( item6, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item1.AddSizer( item3, 0, wxALIGN_CENTER_HORIZONTAL|wxRIGHT|wxBOTTOM, 15 )

    item0.AddSizer( item1, 0, wxALIGN_CENTRE|wxALL, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_CONFIGWEBLOG = 10017
wxID_Cancel = 5101
wxID_Ok = 5100

def ConfigFunc( parent, call_fit = true, set_sizer = true ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item2 = wxNotebook( parent, ID_CONFIGWEBLOG, wxDefaultPosition, wxSize(400,300), 0 )
    item1 = wxNotebookSizer( item2 )

    item3 = wxPanel( item2, -1 )
    ConfigWeblogFunc( item3, false )
    item2.AddPage( item3, "Weblog/XML-RPC" )

    item4 = wxPanel( item2, -1 )
    ConfigUiFunc( item4, false )
    item2.AddPage( item4, "User Interface" )

    item5 = wxPanel( item2, -1 )
    ConfigNetworkFunc( item5, false )
    item2.AddPage( item5, "Network" )

    item6 = wxPanel( item2, -1 )
    ConfigFsFunc( item6, false )
    item2.AddPage( item6, "Files" )

    item0.AddSizer( item1, 0, wxALIGN_CENTRE|wxALL, 5 )

    item7 = wxBoxSizer( wxHORIZONTAL )
    
    item8 = wxButton( parent, wxID_Cancel, "Cancel", wxDefaultPosition, wxDefaultSize, 0 )
    item7.AddWindow( item8, 0, wxALIGN_CENTRE|wxALL, 5 )

    item9 = wxButton( parent, wxID_Ok, "OK", wxDefaultPosition, wxDefaultSize, 0 )
    item7.AddWindow( item9, 0, wxALIGN_CENTRE|wxALL, 5 )

    item0.AddSizer( item7, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_CWLOGSERVER = 10018
ID_CWLOGUSER = 10019
ID_CWLOGPASSWORD = 10020
ID_CWLOGMETAAPI = 10021
ID_CWLOGSETDATE = 10022
ID_CWLOGAGGREGATOR = 10023
ID_CWLOGDEBUG = 10024
ID_CWLOGAUTODETECT = 10025

def ConfigWeblogFunc( parent, call_fit = true, set_sizer = true ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item1 = wxFlexGridSizer( 0, 2, 0, 0 )
    
    item2 = wxStaticText( parent, ID_TEXT, "Server", wxDefaultPosition, wxDefaultSize, 0 )
    item1.AddWindow( item2, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item3 = wxTextCtrl( parent, ID_CWLOGSERVER, "", wxDefaultPosition, wxSize(200,-1), 0 )
    item1.AddWindow( item3, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item4 = wxStaticText( parent, ID_TEXT, "Username", wxDefaultPosition, wxDefaultSize, 0 )
    item1.AddWindow( item4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item5 = wxTextCtrl( parent, ID_CWLOGUSER, "", wxDefaultPosition, wxSize(80,-1), 0 )
    item1.AddWindow( item5, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item6 = wxStaticText( parent, ID_TEXT, "Password", wxDefaultPosition, wxDefaultSize, 0 )
    item1.AddWindow( item6, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item7 = wxTextCtrl( parent, ID_CWLOGPASSWORD, "", wxDefaultPosition, wxSize(80,-1), 0 )
    item1.AddWindow( item7, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item8 = wxStaticText( parent, ID_TEXT, "Supported API Features", wxDefaultPosition, wxDefaultSize, 0 )
    item1.AddWindow( item8, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item9 = wxFlexGridSizer( 0, 2, 0, 0 )
    
    item10 = wxCheckBox( parent, ID_CWLOGMETAAPI, "metaWeblog API", wxDefaultPosition, wxDefaultSize, 0 )
    item10.SetValue(true)
    item9.AddWindow( item10, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item11 = wxCheckBox( parent, ID_CWLOGSETDATE, "SetDate", wxDefaultPosition, wxDefaultSize, 0 )
    item9.AddWindow( item11, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item12 = wxCheckBox( parent, ID_CWLOGAGGREGATOR, "aggregator API", wxDefaultPosition, wxDefaultSize, 0 )
    item9.AddWindow( item12, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item13 = wxCheckBox( parent, ID_CWLOGDEBUG, "XML-RPC debugging", wxDefaultPosition, wxDefaultSize, 0 )
    item9.AddWindow( item13, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item9.AddSpacer( 20, 20, 0, wxALIGN_CENTRE|wxALL, 5 )

    item14 = wxButton( parent, ID_CWLOGAUTODETECT, "Autodetect", wxDefaultPosition, wxDefaultSize, 0 )
    item14.SetToolTip( wxToolTip("Autodetect The Servers Capabilities") )
    item9.AddWindow( item14, 0, wxALIGN_CENTRE|wxALL, 5 )

    item1.AddSizer( item9, 0, wxALIGN_CENTRE|wxALL, 5 )

    item0.AddSizer( item1, 0, wxALIGN_CENTRE|wxALL, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_CUIITEMS = 10026
ID_CUIDELAFTERPOST = 10027
ID_CUIAUTOPREVIEW = 10028

def ConfigUiFunc( parent, call_fit = true, set_sizer = true ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item1 = wxFlexGridSizer( 0, 2, 0, 0 )
    
    item2 = wxStaticText( parent, ID_TEXT, "items on newspage", wxDefaultPosition, wxDefaultSize, 0 )
    item1.AddWindow( item2, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item3 = wxSpinCtrl( parent, ID_CUIITEMS, "23", wxDefaultPosition, wxSize(100,-1), wxSP_ARROW_KEYS|wxSP_WRAP, 1, 1000, 23 )
    item1.AddWindow( item3, 0, wxALIGN_CENTRE|wxALL, 5 )

    item4 = wxStaticText( parent, ID_TEXT, "misc. options", wxDefaultPosition, wxDefaultSize, 0 )
    item1.AddWindow( item4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item5 = wxCheckBox( parent, ID_CUIDELAFTERPOST, "delete item after posting", wxDefaultPosition, wxDefaultSize, 0 )
    item5.SetValue(true)
    item1.AddWindow( item5, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item1.AddSpacer( 20, 20, 0, wxALIGN_CENTRE|wxALL, 5 )

    item6 = wxCheckBox( parent, ID_CUIAUTOPREVIEW, "automatic preview", wxDefaultPosition, wxDefaultSize, 0 )
    item1.AddWindow( item6, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item0.AddSizer( item1, 0, wxALIGN_CENTRE|wxALL, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_CNETTIMEOUT = 10029

def ConfigNetworkFunc( parent, call_fit = true, set_sizer = true ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item1 = wxFlexGridSizer( 0, 2, 0, 0 )
    
    item2 = wxStaticText( parent, ID_TEXT, "Timeout", wxDefaultPosition, wxDefaultSize, 0 )
    item1.AddWindow( item2, 0, wxALIGN_CENTRE|wxALL, 5 )

    item3 = wxSpinCtrl( parent, ID_CNETTIMEOUT, "0", wxDefaultPosition, wxSize(100,-1), wxSP_WRAP, 0, 3600, 0 )
    item1.AddWindow( item3, 0, wxALIGN_CENTRE|wxALL, 5 )

    item0.AddSizer( item1, 0, wxALIGN_CENTRE|wxALL, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_CFSDBDIR = 10030

def ConfigFsFunc( parent, call_fit = true, set_sizer = true ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item1 = wxFlexGridSizer( 0, 2, 0, 0 )
    
    item2 = wxStaticText( parent, ID_TEXT, "database directory", wxDefaultPosition, wxDefaultSize, 0 )
    item1.AddWindow( item2, 0, wxALIGN_CENTRE|wxALL, 5 )

    item3 = wxTextCtrl( parent, ID_CFSDBDIR, "", wxDefaultPosition, wxSize(160,-1), 0 )
    item1.AddWindow( item3, 0, wxALIGN_CENTRE|wxALL, 5 )

    item0.AddSizer( item1, 0, wxALIGN_CENTRE|wxALL, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXTCTRL = 10031

def ServiceDialogFunc( parent, call_fit = true, set_sizer = true ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item2 = wxStaticBox( parent, -1, "Information about Aggregation" )
    item1 = wxStaticBoxSizer( item2, wxVERTICAL )
    
    item3 = wxFlexGridSizer( 0, 2, 0, 0 )
    
    item4 = wxStaticText( parent, ID_TEXT, "Last Request", wxDefaultPosition, wxDefaultSize, 0 )
    item3.AddWindow( item4, 0, wxALIGN_CENTRE|wxALL, 5 )

    item5 = wxStaticText( parent, ID_TEXT, "text", wxDefaultPosition, wxDefaultSize, 0 )
    item3.AddWindow( item5, 0, wxALIGN_CENTRE|wxALL, 5 )

    item6 = wxStaticText( parent, ID_TEXT, "Items fetched", wxDefaultPosition, wxDefaultSize, 0 )
    item3.AddWindow( item6, 0, wxALIGN_CENTRE|wxALL, 5 )

    item7 = wxStaticText( parent, ID_TEXT, "text", wxDefaultPosition, wxDefaultSize, 0 )
    item3.AddWindow( item7, 0, wxALIGN_CENTRE|wxALL, 5 )

    item8 = wxStaticText( parent, ID_TEXT, "Last new Item", wxDefaultPosition, wxDefaultSize, 0 )
    item3.AddWindow( item8, 0, wxALIGN_CENTRE|wxALL, 5 )

    item9 = wxStaticText( parent, ID_TEXT, "text", wxDefaultPosition, wxDefaultSize, 0 )
    item3.AddWindow( item9, 0, wxALIGN_CENTRE|wxALL, 5 )

    item10 = wxStaticText( parent, ID_TEXT, "Errors", wxDefaultPosition, wxDefaultSize, 0 )
    item3.AddWindow( item10, 0, wxALIGN_CENTRE|wxALL, 5 )

    item11 = wxStaticText( parent, ID_TEXT, "text", wxDefaultPosition, wxDefaultSize, 0 )
    item3.AddWindow( item11, 0, wxALIGN_CENTRE|wxALL, 5 )

    item12 = wxStaticText( parent, ID_TEXT, "Last Error", wxDefaultPosition, wxDefaultSize, 0 )
    item3.AddWindow( item12, 0, wxALIGN_CENTRE|wxALL, 5 )

    item13 = wxStaticText( parent, ID_TEXT, "text", wxDefaultPosition, wxDefaultSize, 0 )
    item3.AddWindow( item13, 0, wxALIGN_CENTRE|wxALL, 5 )

    item14 = wxStaticText( parent, ID_TEXT, "Last Error Text", wxDefaultPosition, wxDefaultSize, 0 )
    item3.AddWindow( item14, 0, wxALIGN_CENTRE|wxALL, 5 )

    item15 = wxStaticText( parent, ID_TEXT, "text", wxDefaultPosition, wxDefaultSize, 0 )
    item3.AddWindow( item15, 0, wxALIGN_CENTRE|wxALL, 5 )

    item1.AddSizer( item3, 0, wxALIGN_CENTRE|wxALL, 5 )

    item0.AddSizer( item1, 0, wxALIGN_CENTRE|wxALL, 5 )

    item17 = wxStaticBox( parent, -1, "Information provided by the feed" )
    item16 = wxStaticBoxSizer( item17, wxVERTICAL )
    parent.rsssizer = item16
    
    item18 = wxTextCtrl( parent, ID_TEXTCTRL, "", wxDefaultPosition, wxSize(180,40), wxTE_MULTILINE )
    item16.AddWindow( item18, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item0.AddSizer( item16, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item19 = wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL )
    item0.AddWindow( item19, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item20 = wxFlexGridSizer( 0, 2, 0, 0 )
    
    item21 = wxStaticText( parent, ID_TEXT, "Name", wxDefaultPosition, wxDefaultSize, 0 )
    item20.AddWindow( item21, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item22 = wxTextCtrl( parent, ID_TEXTCTRL, "", wxDefaultPosition, wxSize(180,-1), 0 )
    item20.AddWindow( item22, 0, wxGROW|wxALL, 5 )

    item0.AddSizer( item20, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item23 = wxBoxSizer( wxHORIZONTAL )
    
    item24 = wxButton( parent, ID_REFRESH, "Refresh", wxDefaultPosition, wxDefaultSize, 0 )
    item23.AddWindow( item24, 0, wxALIGN_CENTRE|wxALL, 5 )

    item23.AddSpacer( 20, 20, 0, wxALIGN_CENTRE|wxALL, 5 )

    item25 = wxButton( parent, wxID_CANCEL, "Cancel", wxDefaultPosition, wxDefaultSize, 0 )
    item23.AddWindow( item25, 0, wxALIGN_CENTRE|wxALL, 5 )

    item26 = wxButton( parent, wxID_OK, "OK", wxDefaultPosition, wxDefaultSize, 0 )
    item23.AddWindow( item26, 0, wxALIGN_CENTRE|wxALL, 5 )

    item0.AddSizer( item23, 0, wxALIGN_CENTRE|wxALL, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

ID_PREFERENCES = 10032
ID_File = 10033
ID_HELP = 10034

def MenuBarFunc():
    item0 = wxMenuBar()
    
    item1 = wxMenu()
    item1.Append( ID_PREFERENCES, "Preferences", "" )
    item0.Append( item1, "File" )
    
    item2 = wxMenu()
    item0.Append( item2, "Help" )
    
    return item0

# Toolbar functions

ID_TOOL = 10035

def MainToolBarFunc( parent ):
    parent.SetMargins( [2,2] )
    
    parent.AddSimpleTool( ID_TOOL, wxBitmap( 16, 15, -1 ), "" )
    
    parent.Realize()

# Bitmap functions


# End of generated file
